# Generated by Django 5.0.6 on 2026-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('embedding', models.JSONField(default=list)),
                ('chunk_index', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['article', 'chunk_index'],
            },
        ),
    ]
