# Generated by Django 5.0.6 on 2026-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('guides', 'Travel Guides'), ('culture', 'Local Culture'), ('trekking', 'Trekking'), ('wildlife', 'Wildlife'), ('history', 'History')], default='guides', max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('read_time', models.IntegerField(default=5, help_text='Minutes')),
                ('views', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
