# Generated by Django 5.0.6 on 2026-05-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('landscapes', 'Landscapes'), ('wildlife', 'Wildlife'), ('activities', 'Activities'), ('seasons', 'Seasons')], default='landscapes', max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
